#spring.application.name=EurekaService
#######spring.application.name=EurekaService
######server.port=8790
# we don't need to register  eureka
#####eureka.client.register-with-eureka=false
# we don't need to fetch  registry
#####eureka.client.fetch-registry=false

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: EurekaService