#spring.application.name=ReferentielService
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8071
spring:
  application:
    name: ReferentielService

  datasource:
    url: jdbc:mysql://localhost:3306/Referentiel?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs

management:
  tracing:
    sampling:
      probability: 1.0