package com.esprit.scoringservice.web.model;

public enum ClientCategory {
    ASSURANCES,BANQUE,ENTRPRENEUR_INDIVIDUEL,GRANDE_ENTREPRISE_PRIVE,
    PROFESSION_LIBERALE,GRANDE_ENTREPRISE_PUBLIQUE,PERSONNE_MORALE_PUBLIQUE,PERSONNE_MORALE_PRIVEE
}
